---
# file: roles/mongodb/defaults/main.yml
home_dir: /home/ansible
replicaSetName: rs0
mongodb:
  version: 4.4
  port: 27017
  user: mongodb
  group: mongodb
  key_file: /etc/mongodb.key
  data_path: /var/lib/mongodb/
  log_path: /var/log/mongodb/