---
# file: roles/mongo/main.yml
- name: Add MongoDB repository key
  become: yes
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb.version }}.asc"
    state: present

- name: Add MongoDB repository
  become: yes
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb.version }} multiverse"
    state: present

- name: Install MongoDB
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes
    state: present
  notify: restart mongod