---
# file: roles/basic/tasks/main.yml
- name: Install apt packages
  become: yes
  apt:
    name: "{{ apt_packages}}"
    cache_valid_time: 86400
    update_cache: yes

- name: Install pip packages
  pip:
    name: "{{ pip_packages}}"

- name: Get package facts
  package_facts: