$ANSIBLE_VAULT;1.1;AES256
31396437616165616634306163666539616461343336336566393263653633346366393837366338
3066356265333835346462313061373032643834343231390a343132323037643161306338653861
31346163313064353363376237643464666439623339323739623639353430653831636137373033
3538383133313033370a363565623766346131353131386430663063333334323833666632316461
61303564623130643835613334313763366563366163353763373761643739303363326663666537
39663033636534353061373565386562396433316630653330323666663862366534656235363165
643639303363616162373061623935393261